=== hansdejong/hansdejong.github.io/statics/planten/Planten.xsd
<?xml version="1.0"?>

<!--Hans-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  
  <xsd:annotation>
    <xsd:documentation>Planten-schema.</xsd:documentation>
  </xsd:annotation>
  
  <xsd:element name="planten" type="phylumListType"/>
  
  <xsd:complexType name="phylumListType">
    <xsd:sequence>
      <xsd:element name="phylum" type="classisListType" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="classisListType">
    <xsd:sequence>
      <xsd:element name="classis" type="ordoListType" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="ned" type="xsd:string" use="required"/>
    <xsd:attribute name="lat" type="xsd:string" use="required"/>
    <xsd:attribute name="ook" type="xsd:string"/>
  </xsd:complexType>
  
  <xsd:complexType name="ordoListType">
    <xsd:sequence>
      <xsd:element name="ordo" type="familiaListType" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="ned" type="xsd:string" use="required"/>
    <xsd:attribute name="lat" type="xsd:string" use="required"/>
    <xsd:attribute name="ook" type="xsd:string"/>
  </xsd:complexType>
  
  <xsd:complexType name="familiaListType">
    <xsd:sequence>
      <xsd:element name="familia" type="speciesListType" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="ned" type="xsd:string" use="required"/>
    <xsd:attribute name="lat" type="xsd:string" use="required"/>
    <xsd:attribute name="fam" type="xsd:string" use="required"/>
    <xsd:attribute name="ook" type="xsd:string"/>
  </xsd:complexType>
  
  <xsd:complexType name="speciesListType">
    <xsd:sequence>
      <xsd:element name="species" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:attribute name="ned" type="xsd:string" use="required"/>
          <xsd:attribute name="lat" type="xsd:string" use="required"/>
          <xsd:attribute name="info" type="xsd:string"/>
          <xsd:attribute name="plaatje" type="xsd:string"/>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="ned" type="xsd:string" use="required"/>
    <xsd:attribute name="lat" type="xsd:string" use="required"/>
  </xsd:complexType>
  
</xsd:schema>

=== hansdejong/hansdejong.github.io/statics/planten/Planten.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="Planten.xsl" type="text/xsl" ?>
<planten xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Planten.xsd">
  <phylum lat="Lichenen" ned="Korstmossen">
  	<classis lat="..." ned="...">
  		 <ordo lat="..." ned="..." fam="-">
        <familia lat="..." ned="* ...">
          <species lat="Cladonia floerkeana" ned="Rood heidestaartje"/>
          <species lat="Cladonia portentosa" ned="Rendiermos"/>
          <species lat="Cladonia chlorophaea" ned="Bekermos"/>
        </familia>
      </ordo>
  	</classis>
  </phylum>
  <phylum lat="Bryophyta" ned="Mossen">
  	<classis lat="Hepaticae" ned="Levermossen">
  		<ordo lat="Sphaerocarpale" ned="..." fam="-">
        <familia lat="..." ned="* ...">
          <species lat="..." ned="..."/>
        </familia>
      </ordo>
  		<ordo lat="Marchantiales" ned="..." fam="-">
        <familia lat="..." ned="* ...">
          <species lat="..." ned="..."/>
        </familia>
      </ordo>
  		<ordo lat="Calobryales" ned="..." fam="-">
        <familia lat="..." ned="* ...">
          <species lat="..." ned="..."/>
        </familia>
      </ordo>
  		<ordo lat="Jungermanniales" ned="..." fam="-">
        <familia lat="..." ned="* ...">
          <species lat="..." ned="..."/>
        </familia>
      </ordo>
  		<ordo lat="Anthocerotales" ned="..." fam="-">
        <familia lat="..." ned="* ...">
          <species lat="..." ned="..."/>
        </familia>
      </ordo>
  	</classis>
  	<classis lat="Musci" ned="Bladmossen">
  		 <ordo lat="Sphagnidae" ned="Veenmossen" fam="-">
        <familia lat="..." ned="* Alle mossen">
          <species lat="Sphagnum auriculatum" ned="Veenmos"/>
          <species lat="Polytrichum commune" ned="Gewoon haarmos"/>
          <species lat="Polytrichum piliferum" ned="Ruig haarmos"/>
          <species lat="Bryum pseudotriquetrum" ned="Veenknikmos"/>
          <species lat="Pohlia nutans" ned="Gewoon peermos"/>
        </familia>
      </ordo>
  	</classis>
  </phylum>
  <phylum lat="Pteridophyta" ned="Vaatcryptogamen" ook="Varenachtigen">
    <classis lat="Lycopsida" ned="Wolfsklauwen">
  	  <ordo lat="Selaginellales" ned="..." fam="-">
        <familia lat="Selaginellaceae" ned="* Selaginella's">
          <species lat="Selaginella selaginoides" ned="Selaginella"/>
        </familia>
      </ordo>
      <ordo lat="Lycopodiales" ned="Wolfsklauwachtigen" fam="1,2">
        <familia lat="Lycopodiaceae" ned="Wolfsklauwfamilie">
          <species lat="Lycopodium selago" ned="Plompe wolfsklauw"/>
          <species lat="Lycopodium inundatum" ned="Moeraswolfsklauw"/>
          <species lat="Lycopodium annotinum" ned="Stekende wolfsklauw"/>
          <species lat="Lycopodium clavatum" ned="Grote wolfsklauw"/>
          <species lat="Lycopodium tristachyum" ned="Kleine wolfsklauw"/>
        </familia>
        <familia lat="Isoëtaceae" ned="Biesvarenfamilie">
          <species lat="Isóëtes lacustris" ned="Grote biesvaren"/>
          <species lat="Isóëtes echinospora" ned="Stekelbiesvaren"/>
        </familia>
      </ordo>
    </classis>
    <classis lat="Sphenopsida" ned="Paardestaarten" ook="Equisetatae">
      <ordo lat="..." ned="..." fam="3">
        <familia lat="Equisetaceae" ned="Paardenstaartenfamilie">
          <species lat="Equisétum telmateia" ned="Reuzenpaardestaart"/>
          <species lat="Equisétum sylvaticum" ned="Bospaardestaart"/>
          <species lat="Equisétum fluviatile" ned="Holpijp"/>
          <species lat="Equisétum ramosissimum" ned="Vertakte paardestaart"/>
          <species lat="Equisétum hyemale" ned="Schaafstro"/>
          <species lat="Equisétum variegatum" ned="Bonte paardestaart"/>
          <species lat="Equisétum palustre" ned="Lidrus"/>
          <species lat="Equisétum arvense" ned="Heermoes"/>
          <species lat="Equisétum x litorale" ned="Bastaardpaardestaart"/>
        </familia>
      </ordo>
    </classis>
    <classis lat="Filicopsida" ned="Varens" ook="Filicatae">
      <ordo lat="..." ned="..." fam="4-15">
        <familia lat="Ophioglossaceae" ned="Addertongfamilie">
          <species lat="Ophioglossum vulgatum" ned="Addertong"/>
          <species lat="Botrichium lunaria" ned="Maanvaren"/>
        </familia>
        <familia lat="Osmundaceae" ned="Koningsvarenfamilie">
          <species lat="Osmunda regalis" ned="Koningsvaren"/>
        </familia>
        <familia lat="Hypolepidaceae" ned="Adelaarsvarenfamilie">
          <species lat="Pteridium aquilinum" ned="Adelaarsvaren"/>
        </familia>
        <familia lat="Thelypteridaceae" ned="Moerasvarenfamilie">
          <species lat="Oreopteris limbosperma" ned="Stippelvaren"/>
          <species lat="Phegopteris connectilis" ned="Smalle beukvaren" plaatje="h-smallebeukvaren.jpg"/>
          <species lat="Thelypteris palustris" ned="Moerasvaren"/>
        </familia>
        <familia lat="Aspleniaceae" ned="Streepvarenfamilie">
          <species lat="Asplenium ruta-muraria" ned="Muurvaren"/>
          <species lat="Asplenium adiantum-nigrum" ned="Zwartsteel"/>
          <species lat="Asplenium trichomanes" ned="Steenbreekvaren"/>
          <species lat="Asplenium viride" ned="Groensteel"/>
          <species lat="Ceterach officinarum" ned="Schubvaren"/>
          <species lat="Phyllitis scolopendrium" ned="Tongvaren" plaatje="w-tongvaren.jpg"/>
        </familia>
        <familia lat="Athyriaceae" ned="Wijfjesvarenfamilie">
          <species lat="Athyrium filix-femina" ned="Wijfjesvaren"/>
          <species lat="Cystopteris filix-fragilis" ned="Blaasvaren"/>
          <species lat="Gymnocarpium dryopteris" ned="Gebogen driehoeksvaren"/>
          <species lat="Gymnocarpium robertianum" ned="Rechte driehoeksvaren"/>
        </familia>
        <familia lat="Dryopteridaceae" ned="Niervarenfamilie">
          <species lat="Polystichum aculeatum" ned="Stijve naaldvaren" plaatje="w-stijvenaaldvaren.jpg"/>
          <species lat="Dryopteris filix-mas" ned="Mannetjesvaren" plaatje="h-geschubdemannetjesvaren.jpg"/>
          <species lat="Dryopteris dilatata" ned="Brede stekelvaren"/>
          <species lat="Dryopteris carthusiana" ned="Smalle stekelvaren"/>
          <species lat="Dryopteris cristata" ned="Kamvaren"/>

        </familia>
        <familia lat="Blechnaceae" ned="Dubbellooffamilie">
          <species lat="Blechnum spicant" ned="Dubbelloof"/>
        </familia>
        <familia lat="Polpypodiaceae" ned="Eikvarenfamilie">
          <species lat="Polypodium vulgare" ned="Eikvaren"/>
          <species lat="Polypodium interjectum" ned="Brede eikvaren"/>
        </familia>
        <familia lat="Marcileaceae" ned="Pilvarenfamilie">
          <species lat="Pilularia globulifera" ned="Pilvaren"/>
        </familia>
        <familia lat="Salviniaceae" ned="Vlotvarenfamilie">
          <species lat="Salvinea natans" ned="Vlotvaren"/>
        </familia>
        <familia lat="Azolaceae" ned="Kroosvarenfamilie">
		      <species lat="Azolla caroliniana" ned="Kleine kroosvaren"/>
		      <species lat="Azolla filiculoides" ned="Grote kroosvaren" info="Azolla is eigenlijk wel een lullig plantje.\nIk kan misschien wel een tweede regel meegeven?\nGeen link,\nof een plaatje?"/>
        </familia>
      </ordo>
    </classis>
  </phylum>
  <phylum lat="Spermatophyta" ned="Zaadplanten">
    <classis lat="Ginkgoatae" ned="Ginkgo-achtigen">
  		 <ordo lat="..." ned="..." fam="-">
        <familia lat="Ginkgoaceae" ned="* Ginkgo's">
          <species lat="Ginkgo biloba" ned="Ginkgo"/>
        </familia>
      </ordo>
    </classis>
    <classis lat="Coniferopsida" ned="Coniferen" ook="Pinatae, Naaktzadige naaldbomen">
      <ordo lat="..." ned="..." fam="16,17">
        <familia lat="Pinaceae" ned="Dennenfamilie">
          <species lat="Pinus sylvestris" ned="Grove den"/>
          <species lat="Picea abies" ned="Spar"/>
        </familia>
        <familia lat="Cupressaceae" ned="Cypresfamilie">
          <species lat="Juniperus communis" ned="Jeneverbes"/>
        </familia>
      </ordo>
    </classis>
    <classis lat="Taxopsida" ned="Taxusachtigen">
      <ordo lat="..." ned="..." fam="18">
        <familia lat="Taxaceae" ned="Taxussfamilie">
          <species lat="Taxus baccata" ned="Taxus"/>
        </familia>
      </ordo>
    </classis>
  </phylum>
  <phylum lat="Angiospermae" ned="Bloemplanten">
    <classis lat="Dicotyledones" ned="Tweezaadlobbigen">
      <ordo lat="Salicales" ned="..." fam="19">
        <familia lat="Salicaceae" ned="Wilgenfamilie">
          <species lat="Salix" ned="Wilg"/>
          <species lat="Salix" ned="Treurwilg" plaatje="z-treurwilg.jpg"/>
          <species lat="Salix alba" ned="Schietwilg" plaatje="l-schietwilg_vr.jpg"/>
          <species lat="Salix fragilis" ned="Kraakwilg"/>
          <species lat="Salix petrandra" ned="Laurierwilg"/>
          <species lat="Salix triandra" ned="Amandelwilg"/>
          <species lat="Salix purpurea" ned="Bittere wilg"/>
          <species lat="Salix viminalis" ned="Katwilg"/>
          <species lat="Salix x dasyclados" ned="Duitse dot"/>
          <species lat="Salix caprea" ned="Boswilg"/>
          <species lat="Salix cinerea" ned="Grauwe wilg"/>
          <species lat="Salix aurita" ned="Geoorde wilg"/>
          <species lat="Salix repens" ned="Kruipwilg"/>
          <species lat="Populus nigra" ned="Zwarte populier"/>
          <species lat="Populus alba" ned="Witte abeel"/>
          <species lat="Populus x canescens" ned="Grauwe abeel"/>
          <species lat="Populus tremula" ned="Esp of Ratelpopulier"/>
        </familia>
      </ordo>
      <ordo lat="Myricales" ned="..." fam="20">
        <familia lat="Myricaceae" ned="Gagelfamilie">
          <species lat="Myrica gale" ned="Gagel"/>
        </familia>
      </ordo>
      <ordo lat="Junglandales" ned="..." fam="21">
        <familia lat="Junglandaceae" ned="Okkernootfamilie">
