=== hansdejong/hansdejong.github.io/statics/treeview/Design.xsd
<?xml version="1.0"?>
<!--Hans-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  
	  <xsd:annotation>
		    <xsd:documentation>Planten-sleutel.</xsd:documentation>
	  </xsd:annotation>
	  
	  <xsd:element name="key" type="nodeListType"/>
	
	  <xsd:complexType name="nodeListType">
        <xsd:group ref="choicesGroup" minOccurs="0" maxOccurs="unbounded"/>
	  </xsd:complexType>
	
	  <xsd:complexType name="nodeType">
<!--    <xsd:group ref="choicesGroup" minOccurs="0" maxOccurs="unbounded"/>-->
		    <xsd:group ref="choicesGroup" maxOccurs="unbounded"/>
		    <xsd:attribute name="id" type="xsd:string"/>
		    <xsd:attribute name="choice" type="xsd:string" use="required"/>
   		  <xsd:attribute name="tooltip" type="xsd:string"/>
	  </xsd:complexType>
	
	  <xsd:complexType name="leafType">
		    <xsd:attribute name="id" type="xsd:string"/>
		    <xsd:attribute name="choice" type="xsd:string" use="required"/>
		    <xsd:attribute name="lat" type="xsd:string" use="required"/>
		    <xsd:attribute name="ned" type="xsd:string" use="required"/>
		    <xsd:attribute name="href" type="xsd:string"/>
		    <xsd:attribute name="tooltip" type="xsd:string"/>
		    <xsd:attribute name="genus" type="xsd:string"/>
	  </xsd:complexType>

	  <xsd:complexType name="dummyType"/>
	  
		<xsd:group name="choicesGroup">
			  <xsd:choice>
				    <xsd:element name="node" type="nodeType"/>
				    <xsd:element name="leaf" type="leafType"/>
				    <xsd:element name="dummy" type="dummyType"/>
			  </xsd:choice>
		</xsd:group> 

</xsd:schema>

=== hansdejong/hansdejong.github.io/statics/treeview/Design.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="Design.xsl" type="text/xsl" ?>
<key xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Design.xsd">
  <node id="1" choice="Houtige planten" tooltip="Meer dan 50 cm. hoge heesters of bomen.">
    <node id="1.1a" choice="Bladen aanwezig">
      <node id="1.2a" choice="Klimplant of liaan">
        <node id="1.3a" choice="Blad enkelvoudig, al of niet gelobd of gedeeld">
          <node id="1.4a" choice="Blad handlobbig of -delig">
            <leaf id="1.5a" choice="Plant met ranken, deze tegenover het blad geplaatst" lat="Vitis" ned="Wijnstok" genus="67.2"/>
            <leaf id="1.5b" choice="Plant zonder ranken, met hechtworteltjes op de stengel" lat="Hedera" ned="Klimop" genus="82.1"/>
          </node>
          <leaf id="1.4b" choice="Blad niet gelobd, gaafrandig" lat="Lonicera" ned="Kamperfoelie" genus="108.5"/>
        </node>
        <node id="1.3b" choice="Blad samengesteld">
          <node id="1.6a" choice="Blad handlobbig of -delig">
            <leaf id="1.7a" choice="Plant zonder ranken. Blad drietallig" lat="Rhus radicans" ned="Gifsumak (poison ivy)" genus="59.1"/>
            <leaf id="1.7b" choice="Plant met ranken, deze tegenover het blad geplaatst. Bladen vijftallig" lat="Parthenocissus" ned="Wilde wingerd" genus="67.1"/>
          </node>
          <leaf id="1.6b" choice="Blad veervormig samengesteld" lat="Clematis" ned="Clematis (1e)" genus="40.10"/>
        </node>
      </node>
      <node id="1.2b" choice="Geen klimmende of windende plant">
        <node id="1.8a" choice="Blad samengesteld">
          <node id="1.9a" choice="Bladen kruiswijs">
            <node id="1.10a" choice="Knoppen groen of (schijnbaar) afwezig → 1.11">
              <node id="1.11a" choice="Bladen geveerd → 1.12">
                <leaf id="1.12a" choice="Blaadjes hetzij regelmatig fijn en scherpgezaagd, hetzij in smalle slippen verdeeld" lat="Sambucus" ned="Vlier" genus="108.1"/>
                <leaf id="1.12b" choice="Blaadjes onregelmatig en grof gekarteld-gezaagd, het eindblaadje soms onregelmatig gelobd" lat="Acer negundo" ned="Vederesdoorn (1e)" genus="60.1"/>
              </node>
              <node id="1.11b" choice="Bladen 3 tallig → 1.13">
                <leaf id="1.13a" choice="Blaadjes gaafrandig" lat="Jasminum" ned="Jasmijn" genus="89.4"/>
                <leaf id="1.13b" choice="Blaadjes onregelmatig en grof gekarteld-gezaagd" lat="Acer negundo" ned="Vederesdoorn (2e)" genus="60.1"/>
              </node>
            </node>
            <!--1.10a-->
            <leaf id="1.10b" choice="Donkerbruine of zwarte knoppen aanwezig" lat="Fraxinus" ned="Es" genus="89.1" href="file:///home/hans/Documenten/html/Sort/Planten/Planten.xml#'idFraxinus excelsior'"/>
          </node>
          <!--1.9a-->
          <node id="1.9b" choice="Bladen verspreid → 1.14">
            <node id="1.14a" choice="Plant met dorens of stekels → 1.15">
              <node id="1.15a" choice="Plant met gestekelde twijgen. Blaadjes gezaagd → 1.16">
                <leaf id="1.16a" choice="Steunblaadjes aan een zijde grotendeels met de voet van de bladsteel vergroeid" lat="Rosa" ned="Rosa" genus="50.5"/>
                <leaf id="1.16b" choice="Steunblaadjes bijna tot de voet vrij" lat="Rubus" ned="Braam" genus="50.4"/>
              </node>
              <leaf id="1.15b" choice="Twijg bij de bladvoet met twee dorens. blaadjes vrijwel gaafrandig" lat="Robinia" ned="Robinia" genus="51.6"/>
            </node>
            <node id="1.14b" choice="Plant zonder dorens of stekels → 1.17">
              <node id="1.17a" choice="Blad 3-tallig of handvormig samengesteld → 1.18">
                <leaf id="1.18a" choice="Blad drietallig" lat="Cytisus" ned="Brem" genus="51.2"/>
                <leaf id="1.18b" choice="Blad 5-7 tallig" lat="Aesculus" ned="Paardekastanje" genus="61.1"/>
              </node>
              <node id="1.17b" choice="Blad veervormig samengesteld → 1.19">
                <node id="1.19a" choice="Bladrand gezaagd og getand → 1.20">
                  <leaf id="1.20a" choice="Blaadjes aan de voet met 2-4 grote klieren, aan de voet grof getand" lat="Ailanthus" ned="Hemelboom" genus="57.1"/>
                  <leaf id="1.20b" choice="Blaadjes zonder klieren aan de voet, langs de gehele omtrek scherp gezaagd" lat="Sorbus" ned="Lijsterbes" genus="50.15"/>
                </node>
                <leaf id="1.19b" choice="Bladrand vrijwel gaaf" lat="Juglans" ned="Walnoot" genus="21.1"/>
              </node>
            </node>
          </node>
          <!--1.9b-->
        </node>
        <!--18a-->
        <node id="1.8b" choice="Blad enkelvoudig → 1.21">
          <node id="1.21a" choice="Bladrand gelobd tot gespleten → 1.22">
            <node id="1.22a" choice="Bladen tegenoverstaand → 1.23">
              <leaf id="1.23a" choice="Top van de bladsteel met gesteelde klieren" lat="Viburnum opulus" ned="Gelderse roos" genus="108.2"/>
              <leaf id="1.23b" choice="Gesteelde klieren afwezig" lat="Acer" ned="Esdoorn" tooltip="Indien takken met sterke, naar de bladvoet lopende ribben, vergelijk 89.3 Forsythia/Chinees klokje.              Indien bladsteel korter dan 1/2 cm, vergelijk 108.3 Symphoricarpos/Sneeuwbes"/>
            </node>
            <node id="1.22b" choice="Bladverspreid → 1.24">
              <node id="1.24a" choice="Dorens of stekels aanwezig → 1.25">
                <leaf id="1.25a" choice="Onder elk blad een diep driedelige stekel aanwezig" lat="Ribes uva-crispa" ned="Kruisbes" genus="48.6"/>
                <leaf id="1.25b" choice="Dorens ongedeeld" lat="Crataegus" ned="Meidoorn" genus="50.20"/>
              </node>
              <node id="1.24b" choice="Geen dorens of stekels aanwezig → 1.26">
                <node id="1.26a" choice="Bladonderzijde groen, kaal of behaard → 1.27">
                  <node id="1.27a" choice="Blad handnervig → 1.28">
                    <leaf id="1.28a" choice="Struiken. Bladlobben gekarteld" lat="Ribes" ned="Ribes" genus="48.6"/>
                    <leaf id="1.28b" choice="Bomen. Bladlobben gaaf of met een enkele grove tand" lat="Platanus" ned="Plataan" genus="49.1"/>
                  </node>
                  <leaf id="1.27b" choice="Blad veernervig" lat="Quercus" ned="Eik" genus="24.3"/>
                </node>
                <leaf id="1.26b" choice="Bladonderzijde wit of grijsviltig" lat="Populus" ned="Populier (1e)" genus="19.2"/>
              </node>
            </node>
          </node>
          <node id="1.21b" choice="Bladrand minder dan 1/3 ingesneden → 1.29">
            <node id="1.29a" choice="Bladen hetzij schubvormig, hetzij naald tot lijnvormig en hoogstens 3 mm breed, altijd groen (behalve bij Larix) → 1.30">
              <node id="1.30a" choice="Bladen op korte loten geplaatst, met 2 of meer bijeen, aan de voet door een vliezige schede omgeven → 1.31">
                <leaf id="1.31a" choice="Bladen in elke bundel met meer dan 5" lat="Larix" ned="Lork" genus="16.5"/>
                <leaf id="1.31b" choice="Bladen meeestal 2 (of 5) in elke bundel" lat="Pinus" ned="Den" genus="16.6"/>
              </node>
              <node id="1.30b" choice="Bladen verspreid, tegenoverstaand of in kransen rond de tak geplaatst → 1.32">
                <node id="1.32a" choice="Bladen verspreid → 1.33">
                  <leaf id="1.33a" choice="Twijgen groen, pas in het tweede jaar of later bruin wordend" lat="Taxus" ned="Taxus" genus="18.8"/>
                  <leaf id="1.33b" choice="Twijgen reeds na enkele maanden bruin wordend zodat eenjarige twijgen nooit groen zijn" lat="Pinaceae" ned="Dennenfamilie" genus="16"/>
                </node>
                <node id="1.32b" choice="Bladen tegenoverstaand of in kransen van 3 of 4 → 1.34">
                  <leaf id="1.34a" choice="Bladen aan de voet hetzij steelvormig versmald, hetzij zittend en in 2 priemvormige oortjes verlengd" lat="Erica / Calluna" ned="Dophei / Struikhei" genus="85.1"/>
                  <leaf id="1.34b" choice="Bladen zittend, aan de voet zonder oortjes" lat="Cupressaceae" ned="Cipresfamilie" genus="17"/>
                </node>
              </node>
            </node>
            <node id="1.29b" choice="Bladen niet schub- of naaldvormig; indien lijnvormig dan altijd breder dan 3mm → 1.35">
              <node id="1.35a" choice="Bladen tegenoverstaand → 1.36">
                <node id="1.36a" choice="Blad kaal tot verspreid behaard → 1.37">
                  <node id="1.37a" choice="Plant niet of op elke knoop in tweeen vertakt; geen parasiet → 1.38">
                    <node id="1.38a" choice="Blad gaafrandig of met enkele verspreide insnijdingen → 1.39">
                      <node id="1.39a" choice="Bladen veernervig → 1.40">
                        <node id="1.40a" choice="Bladen kaal of van onderen verspreid behaard → 1.41">
                          <leaf id="1.41a" choice="Bladen met versmalde voet, rondachtig tot elliptisch, van onderen verspreid behaard" lat="Symphoricarpos" ned="Sneeuwbes" genus="108.3"/>
                          <leaf id="1.41b" choice="Bladen of met hartvormige voet, of met versmalde voet en dan elliptisch of lancetvormig en geheel kaal" lat="Oleaceae" ned="Olijffamilie" genus="89"/>
                        </node>
                        <leaf id="1.40b" choice="Bladsteel en de basisvan de middennerf van boven kort en dicht behaard" lat="Buxus" ned="Palmboompje" genus="65.1"/>
                      </node>
                      <leaf id="1.39b" choice="Bladen boognervig" lat="Cornus" ned="Kornoelje" genus="78.1"/>
                    </node>
                    <node id="1.38b" choice="Blad gekarteld of gezaagd → 1.42">
                      <node id="1.42a" choice="Bladen veernervig → 1.43">
                        <leaf id="1.43a" choice="Bast der twijgen groen, niet schilferend" lat="Euonymus" ned="Kardinaalsmuts" genus="64.1"/>
